package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.84

import (
	"context"

	"github.com/pete/go-web/graph/model"
	"github.com/pete/go-web/middleware"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	var products []*model.Product
	if err := loadJSONData("products.json", &products); err != nil {
		return nil, err
	}
	return products, nil
}

// ProductsSmall is the resolver for the productsSmall field.
func (r *queryResolver) ProductsSmall(ctx context.Context) ([]*model.Product, error) {
	var products []*model.Product
	if err := loadJSONData("products-small.json", &products); err != nil {
		return nil, err
	}
	return products, nil
}

// ProductsWithOrders is the resolver for the productsWithOrders field.
func (r *queryResolver) ProductsWithOrders(ctx context.Context) ([]*model.ProductWithOrders, error) {
	// Load the data with a wrapper object
	var wrapper struct {
		Data []*model.ProductWithOrders `json:"data"`
	}
	if err := loadJSONData("products-orders-small.json", &wrapper); err != nil {
		return nil, err
	}
	return wrapper.Data, nil
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*model.Customer, error) {
	var customers []*model.Customer
	if err := loadJSONData("customers-medium.json", &customers); err != nil {
		return nil, err
	}
	return customers, nil
}

// CustomersLarge is the resolver for the customersLarge field.
func (r *queryResolver) CustomersLarge(ctx context.Context) ([]*model.Customer, error) {
	var customers []*model.Customer
	if err := loadJSONData("customers-large.json", &customers); err != nil {
		return nil, err
	}
	return customers, nil
}

// CustomersMedium is the resolver for the customersMedium field.
func (r *queryResolver) CustomersMedium(ctx context.Context) ([]*model.Customer, error) {
	var customers []*model.Customer
	if err := loadJSONData("customers-medium.json", &customers); err != nil {
		return nil, err
	}
	return customers, nil
}

// Photos is the resolver for the photos field.
func (r *queryResolver) Photos(ctx context.Context) ([]*model.Photo, error) {
	var photos []*model.Photo
	if err := loadJSONData("photos.json", &photos); err != nil {
		return nil, err
	}
	return photos, nil
}

// Countries is the resolver for the countries field.
func (r *queryResolver) Countries(ctx context.Context) ([]*model.Country, error) {
	var countries []*model.Country
	if err := loadJSONData("countries.json", &countries); err != nil {
		return nil, err
	}
	return countries, nil
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*model.User, error) {
	// Extract user from context (set by auth middleware)
	user, ok := ctx.Value(middleware.UserContextKey).(*model.User)
	if !ok {
		// No authenticated user
		return nil, nil
	}
	return user, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
